project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /src/languages/en-US/**/*.strings.ts
    translation: /src/languages/%two_letters_code%/**/%original_file_name%