name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    branches:
      - master
    types:
      - completed

jobs:
  determine-image:
    if: github.event.workflow_run.conclusion == 'success'
    name: Determine image to use
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.sha_tag.outputs.tag }}
    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          [[ "${{ github.ref }}" != "refs/tags/"* ]] && tag=sha-$(cut -c 1-7 <<< $GITHUB_SHA)
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && tag=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "::set-output name=tag::$tag"

  prod-deploy:
    environment: production
    needs: determine-image
    if: ${{ !startsWith(needs.determine-image.outputs.tag, 'sha-') }}
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - run: echo "deploying to production with tag ${{ needs.determine-image.outputs.tag }}"
      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v12
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          manifests: |
              manifests/deployment.yaml
          images: 'ghcr.io/thesharks/wildbeast:${{ needs.determine-image.outputs.tag }}'
          kubectl-version: 'latest'
          namespace: wildbeast-staging

  staging-deploy:
    environment: staging
    needs: determine-image
    if: ${{ startsWith(needs.determine-image.outputs.tag, 'sha-') }}
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - run: echo "deploying to staging with tag ${{ needs.determine-image.outputs.tag }}"
      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          manifests: |
              bot/deployment.yaml
          images: 'ghcr.io/thesharks/wildbeast:${{ needs.determine-image.outputs.tag }}'
          kubectl-version: 'latest'
          namespace: wildbeast-production
